/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-28 10:33:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Board.*;
import java.util.*;
import core.*;
import util.*;
import Board.*;
import java.util.*;
import core.*;
import util.*;

public final class smenu31_002dedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/menu/smenu31-left.jsp", Long.valueOf(1449264104888L));
    _jspx_dependants.put("/board/boardEdit2.jsp", Long.valueOf(1451295417941L));
    _jspx_dependants.put("/WEB-INF/include/header.jsp", Long.valueOf(1451296380571L));
    _jspx_dependants.put("/WEB-INF/include/top_menu.jsp", Long.valueOf(1451296294367L));
    _jspx_dependants.put("/WEB-INF/include/footer.jsp", Long.valueOf(1451297931567L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("core");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Board");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>SOOIN SMC :: 수인에스엠씨</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap-dropdown.js\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* sub-left style */\r\n");
      out.write("div#sub-left {\r\n");
      out.write("\tpadding-top: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#sub-right {\r\n");
      out.write("\tpadding-top: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-left h2 {\r\n");
      out.write("\theight: 43px;\r\n");
      out.write("\tborder-bottom: 1px solid #f4f4f4;\r\n");
      out.write("\ttext-indent: 11px;\r\n");
      out.write("\tcolor: #4083c2;\r\n");
      out.write("\tfont-weight: 100;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul, ol {\r\n");
      out.write("\tlist-style: outside none none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-left .smenu:hover, #sub-left .smenu.active {\r\n");
      out.write("\t/* color: #4458a6; */\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #4083c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\toutline: medium none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-left .smenu {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\ttext-indent: 12px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tborder-bottom: 1px solid #f4f4f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-left {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-top: 63px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub {\r\n");
      out.write("\twidth: 980px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tbackground: transparent url(\"/images/sub-bg.gif\") repeat-y scroll 200px\r\n");
      out.write("\t\t0px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* sub-right style */\r\n");
      out.write("#sub-right {\r\n");
      out.write("\twidth: 750px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding: 40px 0px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right .svisual {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 190px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\ttop: 99px;\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset, img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #navi {\r\n");
      out.write("\tcolor: #A6A6A6;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, p, ul, ol, li, dl, dt, dd, form, table, th, td, fieldset, input,\r\n");
      out.write("\ttextarea, select, button, h1, h2, h3, h4, h5, h6, pre {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tfont-family: 나눔고딕, NanumGothic, nanum, \"맑은 고딕\", \"Malgun Gothic\", 돋움,\r\n");
      out.write("\t\tDotum, 굴림, Gulim, Helvetica, applegothic, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #navi span {\r\n");
      out.write("\tcolor: #4C4C4C;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #sub-title {\r\n");
      out.write("    color: #4C4C4C;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    border-bottom: 1px solid #EDEDED;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #sub-title span {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 158px;\r\n");
      out.write("\theight: 12px;\r\n");
      out.write("\tbackground: transparent url(\"/images/sub-title-txt.gif\") no-repeat\r\n");
      out.write("\t\tscroll 0% 0%;\r\n");
      out.write("\ttext-indent: -9999px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tbottom: -3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #content {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tmin-height: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".business-top {\r\n");
      out.write("\theight: 290px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".business-top-left {\r\n");
      out.write("\twidth: 206px;\r\n");
      out.write("\theight: 270px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tpadding: 10px 10px 10px 30px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\t/* background-color: #ba7adf; */\r\n");
      out.write("\tbackground-color: #3AB0D7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".vspace20 {\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\twidth: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".vspace5 {\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("\twidth: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".business-top-right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 544px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clearfix::after {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".business-mid {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table > tr td{\r\n");
      out.write("\tpadding: 10px 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("nav, p, ul, ol, li, dl, dt, dd, form, table, th, td, fieldset, input,\r\n");
      out.write("\ttextarea, select, button, h1, h2, h3, h4, h5, h6, pre {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tfont-family: \"나눔고딕\", NanumGothic, nanum, \"맑은 고딕\", \"Malgun Gothic\", \"돋움\",\r\n");
      out.write("\t\tDotum, \"굴림\", Gulim, Helvetica, applegothic, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top-wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tborder-bottom: 1px solid #cfcfcf;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top {\r\n");
      out.write("\twidth: 980px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 19px 50px 0px 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo, #top #logo a {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo, #top #logo a {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\toutline: medium none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #tnb {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: 50px 50px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul, ol {\r\n");
      out.write("\tlist-style: outside none none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #tnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset, img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 50px 0px 0px 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tpadding: 0px 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttop: 100px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tbackground: rgb(255, 255, 255) none repeat scroll 0% 0%;\r\n");
      out.write("\theight: 105px;\r\n");
      out.write("\t/* border-bottom: 1px solid #E5E5E5; */\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li {\r\n");
      out.write("\twidth: 980px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-left: -320px;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb1 li a:first-child {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb1 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 130px 46px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li #menu /smenu11 {\r\n");
      out.write("\tbackground-image: url(\"/images/picture_suin.png\");\r\n");
      out.write("}\r\n");
      out.write("/*   top #gnb li ul li a:first-child {\r\n");
      out.write("\tborder-left: 1px solid #E5E5E5;\r\n");
      out.write("} \r\n");
      out.write("  #top #gnb li #snb2 li a:first-child {\r\n");
      out.write("    width: 0px;\r\n");
      out.write("} */\r\n");
      out.write("#top #gnb li #snb2 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 150px 46px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb3 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 170px 46px;\r\n");
      out.write("\tmargin-left: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb4 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 200px 46px;\r\n");
      out.write("\tmargin-left: 360px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li a:first-child {\r\n");
      out.write("\t/* border-left: 1px solid #E5E5E5;\r\n");
      out.write("\tborder-right: 1px solid #E5E5E5; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t/* border-right: 2px solid #E5E5E5; */\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu:hover, #top #gnb li .menu.active {\r\n");
      out.write("\tcolor: #4083c2 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tpadding: 0px 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#gnb > .mn\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.bind(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"mouseenter focusin\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:not(#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \")) > ul\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.slideUp(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t100);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \") ul:not(:animated)\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.slideDown(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t200);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:not(#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \")) > .menu\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.removeClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \") .menu\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.addClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\"#top-wrap\").bind(\"mouseleave\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".mn > ul\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t\t\t$(\".menu\").removeClass(\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gnb > .menu\").removeClass(\"over\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");

	String R78 = request.getContextPath();
	boolean isManager = ManagerService.isCurrentUserLoggedIn(session);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav id=\"mbody\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"\" target=\"\" method=\"post\" name=\"f\">\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"\" name=\"reqPKey\"></input>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<div class=\"notipop\"></div>\r\n");
      out.write("\t\t<div class=\"moviewrap\"></div>\r\n");
      out.write("\t\t<div id=\"top-wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t<h1 id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(R78);
      out.write("/main.jsp\"> <img title=\"메인\" alt=\"메인\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/logo_final.png\" width=\"120px\" height=\"80px\"></img></a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<ul id=\"tnb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/main.jsp\"> <img title=\"HOME\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"HOME\" src=\"");
      out.print(R78);
      out.write("/images/home2.png\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						if (!isManager) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/guest/login.jsp\"> <img title=\"로그인\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"로그인\" src=\"");
      out.print(R78);
      out.write("/images/login.png\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/guest/logout.jsp\"> <img title=\"로그아웃\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"로그아웃\" src=\"");
      out.print(R78);
      out.write("/images/login-ok.png\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return confirm('로그아웃 하시겠습니까?');\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul id=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu11.jsp?\"> 회사소개 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb1\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"");
      out.print(R78);
      out.write("/menu/smenu11\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu11.jsp?\"> <img title=\"경영이념\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"경영이념\" src=\"");
      out.print(R78);
      out.write("/images/smenu11-top.jpg\" name=\"smenu11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu11.src='");
      out.print(R78);
      out.write("/images/smenu11-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu11.src='");
      out.print(R78);
      out.write("/images/smenu11-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"");
      out.print(R78);
      out.write("/menu/smenu12\" href=\"");
      out.print(R78);
      out.write("/menu/smenu12.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"찾아오시는 길\" alt=\"찾아오시는 길\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu12-top.jpg\" name=\"smenu12\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu12.src='");
      out.print(R78);
      out.write("/images/smenu12-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu12.src='");
      out.print(R78);
      out.write("/images/smenu12-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu21.jsp?\"> 사업영역 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu21\" href=\"");
      out.print(R78);
      out.write("/menu/smenu21.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"시설영역\" alt=\"시설영역\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu21-top.jpg\" name=\"smenu21\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu21.src='");
      out.print(R78);
      out.write("/images/smenu21-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu21.src='");
      out.print(R78);
      out.write("/images/smenu21-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"menu/smenu22\" href=\"");
      out.print(R78);
      out.write("/menu/smenu22.jsp?\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"보안영역\" alt=\"보안영역\" src=\"");
      out.print(R78);
      out.write("/images/smenu22-top.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"smenu22\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu22.src='");
      out.print(R78);
      out.write("/images/smenu22-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu22.src='");
      out.print(R78);
      out.write("/images/smenu22-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"menu/smenu23\" href=\"");
      out.print(R78);
      out.write("/menu/smenu23.jsp?\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"미화영역\" alt=\"미화영역\" src=\"");
      out.print(R78);
      out.write("/images/smenu23-top.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"smenu23\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu23.src='");
      out.print(R78);
      out.write("/images/smenu23-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu23.src='");
      out.print(R78);
      out.write("/images/smenu23-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu31.jsp?\"> 수인광장 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb3\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu31\" href=\"");
      out.print(R78);
      out.write("/menu/smenu31.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"수인소식\" alt=\"수인소식\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu31-top.jpg\" name=\"smenu31\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu31.src='");
      out.print(R78);
      out.write("/images/smenu31-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu31.src='");
      out.print(R78);
      out.write("/images/smenu31-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu41.jsp?\"> 견적의뢰 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb4\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu41\" href=\"");
      out.print(R78);
      out.write("/menu/smenu41.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"견적의뢰\" alt=\"견적의뢰\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu41-top.jpg\" name=\"smenu41\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu41.src='");
      out.print(R78);
      out.write("/images/smenu41-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu41.src='");
      out.print(R78);
      out.write("/images/smenu41-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"sub\">\r\n");
      out.write("\t\t<div id=\"sub-left\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>NOTICE</h2>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li>\r\n");
      out.write("\t<a class='smenu active' href='");
      out.print(request.getContextPath() );
      out.write("/menu/smenu31.jsp'>수인소식</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"sub-right\">\r\n");
      out.write("\t\t\t<span class=\"svisual\"> \r\n");
      out.write("\t\t\t<img alt=\"서브아이콘\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(R78 );
      out.write("/images/smenu31-icon.png\" width=\"50\" height=\"50\"></img>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<p id=\"navi\">\r\n");
      out.write("\t\t\t\tHome > 수인광장 > 수인소식 <span></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<h3 id=\"sub-title\" class=\"crbold\">\r\n");
      out.write("\t\t\t\t수인소식 <span> 믿을수있는 수인 </span>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<p></p>\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("form>div {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form>div:FIRST-CHILD {\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub-right #content{\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#type {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#value {\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\tcolor: #989898;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder: 1px solid #ededed;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-bottom: 1px solid #d4d4d4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("    border: 1px solid #b4b4b4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tline-height: 1.42857;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground-color: #F4F4F4;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#cancel\").click(function() {\r\n");
      out.write("\t\t\tlocation.href = viewUrl;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");



	String infoMsg = null;
	RequestParameter param = new RequestParameter(request);
	int id = param.getInt("id", 0);
	Board board = BoardDAO1.selectByNum(id);

	String listUrl = request.getContextPath()+"/menu/smenu31.jsp?";
	String viewUrl = request.getContextPath()+"/menu/smenu31-view.jsp?id=" + id;
	
	String title = param.getString("title", board.getTitle());
	String content = param.getString("content", board.getContent());
	content = BoardDAO1.change_Code(content, "<br>", "");
			
	
	String cmd = param.getString("cmd", "");

	if (request.getMethod().equals("POST")) {
		if ("저장".equals(cmd)) {
			BoardDAO1.updateInfo(id, title, content);
			infoMsg = "저장되었습니다";
			response.sendRedirect(viewUrl);
		
		}else if("취소".endsWith(cmd)){
			response.sendRedirect(viewUrl);
		}
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<span style=\"color:#4083C2\">글제목</span> \r\n");
      out.write("\t\t<input id=\"title\" type=\"text\" name=\"title\" value=\"");
      out.print(title);
      out.write("\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<textarea id=\"content\" name=\"content\">");
      out.print(content);
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<button id=\"save\" type=\"submit\" class=\"btn\" name=\"cmd\" value=\"저장\">\r\n");
      out.write("\t\t\t<i class=\"icon-ok\"></i> 저장\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button id=\"cancle\" type=\"submit\" class=\"btn\" name=\"cmd\" value=\"취소\"\r\n");
      out.write("\t\t\tonclick=\"return confirm('글 수정을 취소하시겠습니까?');\">\r\n");
      out.write("\t\t\t<i class=\"icon-remove\"></i> 취소\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<a href=\"");
      out.print(listUrl);
      out.write("\" class=\"btn\"> <i class=\"icon-list\"></i>\r\n");
      out.write("\t\t\t목록으로\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");

	if (infoMsg != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-info\">");
      out.print(infoMsg);
      out.write("</div>\r\n");

	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#bottom{\r\n");
      out.write("    display:block;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    height:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bottom-img{\r\n");
      out.write("    padding:10px 75px;\r\n");
      out.write("    text-align:cetner;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\" id=\"bottom\">\r\n");
      out.write("        <img id=\"bottom-img\" alt=\"수인\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/bottom.png\" width=\"810px\">\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
