/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-28 10:21:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Board.*;
import java.util.*;
import core.*;
import util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/include/header.jsp", Long.valueOf(1451296380571L));
    _jspx_dependants.put("/WEB-INF/include/top_menu.jsp", Long.valueOf(1451296294367L));
    _jspx_dependants.put("/WEB-INF/include/footer.jsp", Long.valueOf(1451297931567L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("core");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Board");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>SOOIN SMC :: 수인에스엠씨</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap-dropdown.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".main {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#image {\r\n");
      out.write("\tbackground-color: #f4f4f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element {\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element .etitle {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 25px;\r\n");
      out.write("\tleft: 20px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #4083c2;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".element-container {\r\n");
      out.write("\twidth: 810px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e1 {\r\n");
      out.write("\twidth: 240px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tborder-right: 1px solid #f4f4f4;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tleft: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e1 .etitle {\r\n");
      out.write("\tleft: 27px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e1 table {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\ttop: 65px;\r\n");
      out.write("\tleft: 25px;\r\n");
      out.write("\tborder-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tborder-spacing: 0px;\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr:hover td {\r\n");
      out.write("\tcolor: #4083c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e1 table td {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tcolor: #4d4d4d;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e2 {\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tborder-right: 1px solid #f4f4f4;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tleft: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e3 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 210px;\r\n");
      out.write("\tleft: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e3 .e3-1 {\r\n");
      out.write("\ttop: 65px;\r\n");
      out.write("\tbackground: transparent url(images/guin4.png) no-repeat scroll 50% 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e3 .e3-2 {\r\n");
      out.write("\ttop: 65px;\r\n");
      out.write("\tleft: 120px;\r\n");
      out.write("\tbackground: transparent url(images/gugik4.png) no-repeat scroll 0% 0%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#element #e3 a {\r\n");
      out.write("\ttop: 20px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 30px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\ttext-indent: 54px;\r\n");
      out.write("\tline-height: 49px;\r\n");
      out.write("\tpadding-right: 7px;\r\n");
      out.write("\theight: 49px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* #element #e3 a {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 25px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    padding-right: 7px;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    text-indent: 54px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("} */\r\n");
      out.write("#element #e3 .e3-icon {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bottom {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"tbody tr\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/menu/smenu31-view.jsp?id=\"\r\n");
      out.write("\t\t\t\t\t\t\t+ $(this).attr(\"data-id\") + \"&\"\r\n");
      out.write("\t\t\t\t\t\t\t+ location.search.replace(\"?\", \"\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t$(\"div.pagination a\").click(function() {\r\n");
      out.write("\t\t\t$(\"input[name=pg]\").val($(this).attr(\"data-page\"));\r\n");
      out.write("\t\t\t$(\"form\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

	String s = request.getParameter("pg");
	int currentPage = (s == null) ? 1 : Integer.parseInt(s);
	int pageSize = 10;
	ArrayList<Board> list = BoardDAO1.selectPage(currentPage, pageSize);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("nav, p, ul, ol, li, dl, dt, dd, form, table, th, td, fieldset, input,\r\n");
      out.write("\ttextarea, select, button, h1, h2, h3, h4, h5, h6, pre {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tfont-family: \"나눔고딕\", NanumGothic, nanum, \"맑은 고딕\", \"Malgun Gothic\", \"돋움\",\r\n");
      out.write("\t\tDotum, \"굴림\", Gulim, Helvetica, applegothic, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top-wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tborder-bottom: 1px solid #cfcfcf;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top {\r\n");
      out.write("\twidth: 980px;\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 19px 50px 0px 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo, #top #logo a {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #logo, #top #logo a {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\toutline: medium none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #tnb {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin: 50px 50px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul, ol {\r\n");
      out.write("\tlist-style: outside none none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #tnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset, img {\r\n");
      out.write("\tborder: 0px none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 50px 0px 0px 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tpadding: 0px 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttop: 100px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tbackground: rgb(255, 255, 255) none repeat scroll 0% 0%;\r\n");
      out.write("\theight: 105px;\r\n");
      out.write("\t/* border-bottom: 1px solid #E5E5E5; */\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li {\r\n");
      out.write("\twidth: 980px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-left: -320px;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb1 li a:first-child {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb1 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 130px 46px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li #menu /smenu11 {\r\n");
      out.write("\tbackground-image: url(\"/images/picture_suin.png\");\r\n");
      out.write("}\r\n");
      out.write("/*   top #gnb li ul li a:first-child {\r\n");
      out.write("\tborder-left: 1px solid #E5E5E5;\r\n");
      out.write("} \r\n");
      out.write("  #top #gnb li #snb2 li a:first-child {\r\n");
      out.write("    width: 0px;\r\n");
      out.write("} */\r\n");
      out.write("#top #gnb li #snb2 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 150px 46px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb3 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 170px 46px;\r\n");
      out.write("\tmargin-left: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li #snb4 li a {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tbackground-position: 200px 46px;\r\n");
      out.write("\tmargin-left: 360px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li a:first-child {\r\n");
      out.write("\t/* border-left: 1px solid #E5E5E5;\r\n");
      out.write("\tborder-right: 1px solid #E5E5E5; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li ul li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t/* border-right: 2px solid #E5E5E5; */\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu:hover, #top #gnb li .menu.active {\r\n");
      out.write("\tcolor: #4083c2 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top #gnb li .menu {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tpadding: 0px 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#gnb > .mn\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.bind(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"mouseenter focusin\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:not(#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \")) > ul\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.slideUp(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t100);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \") ul:not(:animated)\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.slideDown(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t200);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:not(#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \")) > .menu\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.removeClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#gnb > .mn:eq(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \") .menu\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.addClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\"#top-wrap\").bind(\"mouseleave\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".mn > ul\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t\t\t$(\".menu\").removeClass(\"over\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gnb > .menu\").removeClass(\"over\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");

	String R78 = request.getContextPath();
	boolean isManager = ManagerService.isCurrentUserLoggedIn(session);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav id=\"mbody\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"\" target=\"\" method=\"post\" name=\"f\">\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"\" name=\"reqPKey\"></input>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<div class=\"notipop\"></div>\r\n");
      out.write("\t\t<div class=\"moviewrap\"></div>\r\n");
      out.write("\t\t<div id=\"top-wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t<h1 id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(R78);
      out.write("/main.jsp\"> <img title=\"메인\" alt=\"메인\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/logo_final.png\" width=\"120px\" height=\"80px\"></img></a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<ul id=\"tnb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/main.jsp\"> <img title=\"HOME\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"HOME\" src=\"");
      out.print(R78);
      out.write("/images/home2.png\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						if (!isManager) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/guest/login.jsp\"> <img title=\"로그인\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"로그인\" src=\"");
      out.print(R78);
      out.write("/images/login.png\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(R78);
      out.write("/guest/logout.jsp\"> <img title=\"로그아웃\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"로그아웃\" src=\"");
      out.print(R78);
      out.write("/images/login-ok.png\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return confirm('로그아웃 하시겠습니까?');\" width=\"25px\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"25px\"></img>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul id=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu11.jsp?\"> 회사소개 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb1\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"");
      out.print(R78);
      out.write("/menu/smenu11\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu11.jsp?\"> <img title=\"경영이념\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"경영이념\" src=\"");
      out.print(R78);
      out.write("/images/smenu11-top.jpg\" name=\"smenu11\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu11.src='");
      out.print(R78);
      out.write("/images/smenu11-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu11.src='");
      out.print(R78);
      out.write("/images/smenu11-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"");
      out.print(R78);
      out.write("/menu/smenu12\" href=\"");
      out.print(R78);
      out.write("/menu/smenu12.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"찾아오시는 길\" alt=\"찾아오시는 길\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu12-top.jpg\" name=\"smenu12\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu12.src='");
      out.print(R78);
      out.write("/images/smenu12-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu12.src='");
      out.print(R78);
      out.write("/images/smenu12-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu21.jsp?\"> 사업영역 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb2\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu21\" href=\"");
      out.print(R78);
      out.write("/menu/smenu21.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"시설영역\" alt=\"시설영역\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu21-top.jpg\" name=\"smenu21\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu21.src='");
      out.print(R78);
      out.write("/images/smenu21-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu21.src='");
      out.print(R78);
      out.write("/images/smenu21-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"menu/smenu22\" href=\"");
      out.print(R78);
      out.write("/menu/smenu22.jsp?\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"보안영역\" alt=\"보안영역\" src=\"");
      out.print(R78);
      out.write("/images/smenu22-top.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"smenu22\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu22.src='");
      out.print(R78);
      out.write("/images/smenu22-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu22.src='");
      out.print(R78);
      out.write("/images/smenu22-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a id=\"menu/smenu23\" href=\"");
      out.print(R78);
      out.write("/menu/smenu23.jsp?\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"미화영역\" alt=\"미화영역\" src=\"");
      out.print(R78);
      out.write("/images/smenu23-top.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"smenu23\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu23.src='");
      out.print(R78);
      out.write("/images/smenu23-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu23.src='");
      out.print(R78);
      out.write("/images/smenu23-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu31.jsp?\"> 수인광장 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb3\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu31\" href=\"");
      out.print(R78);
      out.write("/menu/smenu31.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"수인소식\" alt=\"수인소식\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu31-top.jpg\" name=\"smenu31\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu31.src='");
      out.print(R78);
      out.write("/images/smenu31-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu31.src='");
      out.print(R78);
      out.write("/images/smenu31-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"mn\"><a class=\"menu\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(R78);
      out.write("/menu/smenu41.jsp?\"> 견적의뢰 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"snb4\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a id=\"menu/smenu41\" href=\"");
      out.print(R78);
      out.write("/menu/smenu41.jsp?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img title=\"견적의뢰\" alt=\"견적의뢰\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(R78);
      out.write("/images/smenu41-top.jpg\" name=\"smenu41\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseover=\"smenu41.src='");
      out.print(R78);
      out.write("/images/smenu41-top-hover.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonmouseout=\"smenu41.src='");
      out.print(R78);
      out.write("/images/smenu41-top.jpg'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"200px\" height=\"105px\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"main\" id=\"image\">\r\n");
      out.write("        <img id=\"img_to_main\" src=\"pic_src\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            var i = 1;\r\n");
      out.write("\r\n");
      out.write("            function change_pic() {\r\n");
      out.write("                i++;\r\n");
      out.write("                if (i == 4) {\r\n");
      out.write("                    i = 1;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (i == 1) {\r\n");
      out.write("                    document.getElementById('img_to_main').src = \"images/main_13.png\";\r\n");
      out.write("                } else if (i == 2) {\r\n");
      out.write("                    document.getElementById('img_to_main').src = \"images/main_23.png\";\r\n");
      out.write("                } else if (i == 3) {\r\n");
      out.write("                    document.getElementById('img_to_main').src = \"images/main_33.png\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var pic_src = setInterval(change_pic, 3000);\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<div class=\"main\" id=\"element\">\r\n");
      out.write("\t\t<div class=\"element-container\">\r\n");
      out.write("\t\t\t<div id=\"e1\">\r\n");
      out.write("\t\t\t\t<h2 class=\"etitle\" style=\"text-align: left\">수인소식</h2>\r\n");
      out.write("\t\t\t\t<table style=\"line-height: 1.6em;\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
	
								int count = BoardDAO1.getRecordCount();
								if(count == 0){
									out.println("<tr data-id='-1'><td>공지사항이 없습니다.</td></tr>");
								}else{
									for (int i = 0; i < 5; i++) {
										try{
											list.get(i).getId();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr data-id=\"");
      out.print(list.get(i).getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
char[] _title = list.get(i).getTitle().toCharArray();
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
out.print("[" + list.get(i).getDate() + "] ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
	
														if(_title.length > 10){
															for(int j=0; j<10; j++)
																out.print(_title[j]);
																out.print("...");
														}else{
															out.print(list.get(i).getTitle());
														}
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t");

										}catch(IndexOutOfBoundsException e){
											out.println("<tr><td></td></tr>");
											System.out.println(e.toString());
										}
									}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"e2\">\r\n");
      out.write("\t\t\t\t<h2 class=\"etitle\" style=\"text-align: left\">사업영역</h2>\r\n");
      out.write("\t\t\t\t<!-- <img id=\"img_to_main2\" src=\"pic_src2\" width=\"240px\" height=\"130px\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 64px\" /> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t// 스크롤러의 가로크기\r\n");
      out.write("\t\t\t\t\tvar sliderwidth = 240\r\n");
      out.write("\t\t\t\t\t// 스크롤러의 높이 (이미지의 높이와 맞추어 주세요)\r\n");
      out.write("\t\t\t\t\tvar sliderheight = 130\r\n");
      out.write("\t\t\t\t\t// 스크롤 속도 (클수록 빠릅니다 1-10)\r\n");
      out.write("\t\t\t\t\tvar slidespeed = 1\r\n");
      out.write("\t\t\t\t\t// 배경색상\r\n");
      out.write("\t\t\t\t\tslidebgcolor = \"#\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 이미지들을 설정 하세요\r\n");
      out.write("\t\t\t\t\tvar leftrightslide = new Array()\r\n");
      out.write("\t\t\t\t\tvar finalslide = ''\r\n");
      out.write("\t\t\t\t\tleftrightslide[1] = \"<img id='img_to_main2' style='margin-top: 64px' width='240px' height='130px' src='images/main_13.jpg' alt='배너1' />\"\r\n");
      out.write("\t\t\t\t\tleftrightslide[2] = \"<img id='img_to_main2' style='margin-top: 64px' width='240px' height='130px' src='images/main_23.jpg' alt='배너2' />\"\r\n");
      out.write("\t\t\t\t\tleftrightslide[3] = \"<img id='img_to_main2' style='margin-top: 64px' width='240px' height='130px' src='images/main_33.jpg' alt='배너3' />\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar copyspeed = slidespeed\r\n");
      out.write("\t\t\t\t\tleftrightslide = '<nobr>' + leftrightslide.join(\" \")\r\n");
      out.write("\t\t\t\t\t\t\t+ '</nobr>'\r\n");
      out.write("\t\t\t\t\tvar iedom = document.all || document.getElementById\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (iedom)\r\n");
      out.write("\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t.write('<span id=\"temp\" style=\"visibility:hidden;position:absolute;top:-100;left:-4000px\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ leftrightslide + '</span>')\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar actualwidth = ''\r\n");
      out.write("\t\t\t\t\tvar cross_slide, ns_slide\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction fillup() {\r\n");
      out.write("\t\t\t\t\t\tif (iedom) {\r\n");
      out.write("\t\t\t\t\t\t\tcross_slide = document.getElementById ? document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.getElementById(\"test2\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t: document.all.test2\r\n");
      out.write("\t\t\t\t\t\t\tcross_slide2 = document.getElementById ? document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.getElementById(\"test3\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t: document.all.test3\r\n");
      out.write("\t\t\t\t\t\t\tcross_slide.innerHTML = cross_slide2.innerHTML = leftrightslide\r\n");
      out.write("\t\t\t\t\t\t\tactualwidth = document.all ? cross_slide.offsetWidth\r\n");
      out.write("\t\t\t\t\t\t\t\t\t: document.getElementById(\"temp\").offsetWidth\r\n");
      out.write("\t\t\t\t\t\t\tcross_slide2.style.left = actualwidth + 5 + \"px\"\r\n");
      out.write("\t\t\t\t\t\t} else if (document.layers) {\r\n");
      out.write("\t\t\t\t\t\t\tns_slide = document.ns_slidemenu.document.ns_slidemenu2\r\n");
      out.write("\t\t\t\t\t\t\tns_slide2 = document.ns_slidemenu.document.ns_slidemenu3\r\n");
      out.write("\t\t\t\t\t\t\tns_slide.document.write(leftrightslide)\r\n");
      out.write("\t\t\t\t\t\t\tns_slide.document.close()\r\n");
      out.write("\t\t\t\t\t\t\tactualwidth = ns_slide.document.width\r\n");
      out.write("\t\t\t\t\t\t\tns_slide2.left = actualwidth + 5 + \"px\"\r\n");
      out.write("\t\t\t\t\t\t\tns_slide2.document.write(leftrightslide)\r\n");
      out.write("\t\t\t\t\t\t\tns_slide2.document.close()\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tlefttime = setInterval(\"slideleft()\", 30)\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction slideleft() {\r\n");
      out.write("\t\t\t\t\t\tif (iedom) {\r\n");
      out.write("\t\t\t\t\t\t\tif (parseInt(cross_slide.style.left) > (actualwidth\r\n");
      out.write("\t\t\t\t\t\t\t\t\t* (-1) + 5))\r\n");
      out.write("\t\t\t\t\t\t\t\tcross_slide.style.left = parseInt(cross_slide.style.left)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t- copyspeed + \"px\"\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tcross_slide.style.left = parseInt(cross_slide2.style.left)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ actualwidth + 5 + \"px\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (parseInt(cross_slide2.style.left) > (actualwidth\r\n");
      out.write("\t\t\t\t\t\t\t\t\t* (-1) + 5))\r\n");
      out.write("\t\t\t\t\t\t\t\tcross_slide2.style.left = parseInt(cross_slide2.style.left)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t- copyspeed + \"px\"\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tcross_slide2.style.left = parseInt(cross_slide.style.left)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ actualwidth + 5 + \"px\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else if (document.layers) {\r\n");
      out.write("\t\t\t\t\t\t\tif (ns_slide.left > (actualwidth * (-1) + 5))\r\n");
      out.write("\t\t\t\t\t\t\t\tns_slide.left -= copyspeed + \"px\"\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tns_slide.left = ns_slide2.left + actualwidth\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ 5 + \"px\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (ns_slide2.left > (actualwidth * (-1) + 5))\r\n");
      out.write("\t\t\t\t\t\t\t\tns_slide2.left -= copyspeed + \"px\"\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tns_slide2.left = ns_slide.left + actualwidth\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ 5 + \"px\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (iedom || document.layers) {\r\n");
      out.write("\t\t\t\t\t\twith (document) {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.write('<div style=\"padding-top: 3px;\">')\r\n");
      out.write("\t\t\t\t\t\t\tif (iedom) {\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<div style=\"width:'+sliderwidth+'px;height:'+sliderheight+'px;overflow:hidden\">')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<div style=\"padding:5px;position:absolute;width:'+sliderwidth+'px;height:'+sliderheight+'px;background-color:'+slidebgcolor+'\" onfocus=\"copyspeed=0\" onblur=\"copyspeed=slidespeed\" onMouseover=\"copyspeed=0\" onMouseout=\"copyspeed=slidespeed\">')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<div id=\"test2\" style=\"position:absolute;left:0px;top:0px\"></div>')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<div id=\"test3\" style=\"position:absolute;left:-1000px;top:0px\"></div>')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('</div></div>')\r\n");
      out.write("\t\t\t\t\t\t\t} else if (document.layers) {\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<ilayer width='+sliderwidth+' height='+sliderheight+' name=\"ns_slidemenu\" bgColor='+slidebgcolor+'>')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<layer name=\"ns_slidemenu2\" left=\"0px\" top=\"0px\" onfocus=\"copyspeed=0\" onblur=\"copyspeed=slidespeed\" onMouseover=\"copyspeed=0\" onMouseout=\"copyspeed=slidespeed\"></layer>')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('<layer name=\"ns_slidemenu3\" left=\"0px\" top=\"0px\" onfocus=\"copyspeed=0\" onblur=\"copyspeed=slidespeed\" onMouseover=\"copyspeed=0\" onMouseout=\"copyspeed=slidespeed\"></layer>')\r\n");
      out.write("\t\t\t\t\t\t\t\twrite('</ilayer>')\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tfillup();\r\n");
      out.write("\t\t\t\t</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"e3\">\r\n");
      out.write("\t\t\t<h2 class=\"etitle\" style=\"text-align: left\">견적의뢰</h2>\r\n");
      out.write("\t\t\t<div style=\"margin-top: 60px; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t<div class=\"e3-icon\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/info.png\" width=\"240px\" height=\"130px\" />\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#bottom{\r\n");
      out.write("    display:block;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    height:100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bottom-img{\r\n");
      out.write("    padding:10px 75px;\r\n");
      out.write("    text-align:cetner;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\" id=\"bottom\">\r\n");
      out.write("        <img id=\"bottom-img\" alt=\"수인\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/bottom.png\" width=\"810px\">\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
